- name: Install docker and docker-compose
  hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: Install docker packages and other bits
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: present
      update_cache: yes
    tags:
      - docker
  - name: Add Docker official GPG key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
    tags:
      - docker
  - name: Verify that we have the key with the fingerprint
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker
  - name: Set up the stable repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
      state: present
      update_cache: yes
    tags:
      - docker
  - name: Update apt packages
    apt:
      update_cache: yes
    tags:
      - docker
  - name: Check if daemon.json already exists, and skip creating it if so
    tags:
      - docker
    stat:
      path: /etc/docker/daemon.json
    register: daemon_file
  - name: Set up docker daemon.json that enables ipv6
    tags:
      - docker
    when: not daemon_file.stat.exists
    block:
      - name: Ensure path to daemon.json exists
        file:
          path: /etc/docker
          recurse: true
          state: directory
      - name: Create docker daemon.json that enables ipv6
        copy:
          dest: /etc/docker/daemon.json
          force: false
          content: |
            {
              "ipv6": true,
              "fixed-cidr-v6": "{{ outputs['internal_ipv6_range'] }}"
            }
  - name: Install docker
    apt:
      name:
        - containerd.io
        - docker-ce
        - docker-ce-cli
      state: present
      update_cache: yes
    #notify: Start docker on boot
    tags:
      - docker
  - name: Install docker-compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
