solr_assocs:
  url: "http://solr:8983/solr/golr"
  timeout: 60
amigo_solr_assocs:
  url: "http://golr.berkeleybop.org"
  timeout: 4
solr_search:
  url: "http://solr:8983/solr/search"
  timeout: 60
amigo_solr_search:
  url: "http://golr.berkeleybop.org"
  timeout: 2
sparql:
  url: "http://sparql.hegroup.org/sparql"
  timeout: 2
scigraph_ontology:
  url: "http://scigraph-ontology:9000/scigraph/"
  timeout: 60
scigraph_data:
  url: "http://scigraph-data:9000/scigraph/"
  timeout: 60
use_amigo_for:
  - function
identifier_converter: biolink.identifier_converter.SciGraphIdentifierConverter
ontologies:
  - id: go
    handle: go
    pre_load: false
  - id: hp
    handle: hp
    pre_load: false

