version: "3.8"
services:

  solr:
    image: solr:6.6-slim 
    ports:
      - "8983:8983"
    volumes:
      - "${DATADIR}/solr/data:/data"
    environment:
      - "SOLR_HOME=/data"
      - "SOLR_HEAP=50g"
    restart: "unless-stopped"
    networks:
      - "monarchnet"
    healthcheck:
      test: "curl -f localhost:8983/solr/golr/select?q=*:*&rows=1 || exit 1"
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 60s
  
  scigraph-data:
    image: monarchinitiative/scigraph:2.2
    ports:
      - "9000:9000"
    volumes:
      - "${DATADIR}/scigraph-data/data:/data"
      - "${DATADIR}/scigraph-data/conf:/scigraph/conf"
    restart: "unless-stopped"
    command: "start-scigraph-service scigraph-data.yaml"
    networks:
      - "monarchnet"
    healthcheck:
      test: "curl -f localhost:9000/scigraph/graph/HGNC%3A11027 || exit 1"
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 60s

  scigraph-ontology:
    image: monarchinitiative/scigraph:2.2
    ports:
      - "9090:9000"
    volumes:
      - "${DATADIR}/scigraph-ontology/data:/data"
      - "${DATADIR}/scigraph-ontology/conf:/scigraph/conf"
    restart: "unless-stopped"
    command: "start-scigraph-service scigraph-ontology.yaml"
    networks:
      - "monarchnet"
    healthcheck:
      test: "curl -f localhost:9000/scigraph/graph/MONDO:0000001 || exit 1"
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 60s

  owlsim:
    image: monarchinitiative/owlsim:0.3.0
    ports:
      - "9031:9031"
    volumes:
      - "${DATADIR}/owlsim:/data"
    restart: "unless-stopped"
    command: "/bin/sh -c 'export OWLTOOLS_MEMORY=45G && owltools /data/all.owl --use-fsim  --sim-load-lcs-cache /data/owlsim.cache --sim-load-ic-cache /data/ic-cache.owl --start-sim-server -p 9031'"
    networks:
      - "monarchnet"
    healthcheck:
      test: "curl -f localhost:9031/getAttributeInformationProfile || exit 1"
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 20m

networks:
  monarchnet:
    driver: "bridge"
    name: "monarch-network"
