- name: Annotate nodes with roles
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Show services in workers
      debug:
        msg: |
          Worker {{ item }} has services {{ hostvars[item]['vars']['services'] }}
      with_items: "{{ groups['worker'] }}"
        
    - name: Annotate each node with its role
      shell: |
        echo docker node update --label-add services={{ ','.join(item.value.vars.services) }} {{ item.key }}
      loop: "{{ hostvars | dict2items | selectattr('value.vars.services') }}"
      register: output
      
    # - name: Annotate each node with its role
    #   shell: |
    #     docker node update --label-add {{ item.1 }}_svc {{ item.0.key }}
    #   loop: "{{ hostvars | dict2items | subelements('value.vars.services') }}"

    - name: Clean loop output
      set_fact:
        clean_out: "{{ clean_out|default([]) + [item.stdout] }}"
      with_items:
        - "{{ output.results }}"

    - name: Display information from 'show' output
      debug: msg="{{ clean_out }}"
      tags: DEBUG
