- name: Install docker-stack pre-reqs, copy app to all
  hosts: all
  become: yes
  tasks:
    - name: install docker cmd prereqs
      pip:
        name:
          - jsondiff
          - pyyaml
    - name: install rsync prereq
      apt:
        name:
          - rsync
        state: present
        update_cache: yes
    - name: Sync app stack with target
      ansible.posix.synchronize:
        src: ../../stack/
        dest: /stack

- name: Ensure we have docker access to each machine
  hosts: localhost
  tasks:
    - shell: |
        gcloud compute ssh --project=monarch-initiative --zone=us-central1-a \
          {{ item }} -- sudo usermod -a -G docker $USER
      loop: "{{ groups['all'] }}"

- name: Copy letsencrypt to manager
  hosts: manager
  become: yes
  tasks:
    - name: Sync letsencrypt to balancer node
      ansible.posix.synchronize:
        src: ./.secrets/letsencrypt
        dest: /etc

- name: Create local registry, build custom images, deploy stack
  hosts: manager
  become: yes
  tasks:
    - name: Start registry service
      docker_swarm_service:
        name: registry
        image: registry:2
        publish:
          - target_port: 5000
            published_port: 5015
            
    - name: Build and push balancer to our local registry
      community.docker.docker_image:
        build:
          path: /stack/docker-images/balancer
        name: 127.0.0.1:5015/balancer
        tag: 0.0.3
        push: yes
        source: build

    - name: Deploy stack from a compose file
      docker_stack:
        state: present
        name: monarch
        compose:
          - /stack/docker-compose.yml
      environment:
        DATADIR: "/srv/monarch"
