---
- name: Perform initial host setup
  hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: Wait for hosts to come online
    wait_for_connection:
      timeout: 800
  - name: Install core packages, monitoring
    script: ./init_scripts/startup_vm_lite.sh
  - name: Wait for setup script to complete
    wait_for:
      path: /etc/startup_was_launched
  - name: Create /srv/monarch mountpoint
    ansible.builtin.file:
        path: /srv/monarch
        state: directory
  - name: Mount /srv/monarch
    ansible.posix.mount:
      path: /srv/monarch
      src: /dev/disk/by-id/google-monarch-data
      fstype: ext4
      opts: ro
      state: mounted

- name: Run docker setup
  become: yes
  import_playbook: support/setup_docker.yml

- name: Init swarm on manager and join on clients
  hosts: all
  become: yes
  tasks:
    - name: Install python
      apt:
        name:
          - python3
          - python3-pip
          - python-setuptools
        state: present
        update_cache: yes
    - name: Install docker-swarm python reqs
      pip:
        name: docker

    - name: Get manager IP
      when: inventory_hostname in groups['manager']
      shell: hostname -I | cut -d ' ' -f 1
      register: manager_ip

    - name: Init a new swarm with default parameters
      when: inventory_hostname in groups['manager']
      community.general.docker_swarm:
        state: present
      register: init_result

    - name: Print info from manager
      debug:
        msg: |
          Manager IP: {{ hostvars[groups['manager'][0]]['manager_ip'].stdout }}
          Join Token: {{ hostvars[groups['manager'][0]]['init_result']['swarm_facts']['JoinTokens']['Worker'] }}

    - name: Add nodes
      when: inventory_hostname in groups['worker']
      community.general.docker_swarm:
        state: join
        remote_addrs: "{{ hostvars[groups['manager'][0]]['manager_ip'].stdout }}"
        join_token: "{{ hostvars[groups['manager'][0]]['init_result']['swarm_facts']['JoinTokens']['Worker'] }}"

    - name: Run docker node ls
      when: inventory_hostname in groups['manager']
      shell: |
        docker node ls
      register: node_ls_result

    - name: Print docker node info
      when: inventory_hostname in groups['manager']
      debug:
        msg: |
          Nodes: {{ hostvars[groups['manager'][0]]['node_ls_result'].stdout }}

- name: Annotate each node with its role
  hosts: manager
  become: yes
  tasks:
    - shell: |
        docker node update --label-add {{ item.1 }}_svc=true {{ item.0.key }}
      loop: "{{ hostvars | dict2items | subelements('value.vars.services') }}"

- name: Deploy swarm app
  import_playbook: setup_monarch_app.yml
